### ISSUE TITLE
发送频道消息时报错以及一些其他问题（私域QQ频道机器人与公域QQ频道机器人）

### ISSUE THREAD

**Issue by HSTKChiyuki** [lunzhiPenxil/OlivOSOnebotV11#1]
[OlivOSOnebotV11] - 'fake_event' object has no attribute 'extend'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nb\OlivOS-Win-0.11.9\./plugin/tmp\OlivOSOnebotV11\eventRouter.py", line 279, in doRouter
  File "C:\Users\Administrator\Desktop\nb\OlivOS-Win-0.11.9\./plugin/tmp\OlivOSOnebotV11\eventRouter.py", line 496, in send_group_msg
  File "OlivOS\API.py", line 877, in send
  File "OlivOS\API.py", line 787, in __send
AttributeError: 'fake_event' object has no attribute 'extend'
以上报错是发送了一个消息数组
以下报错是发送了一个消息字符串
[OlivOSOnebotV11] - string indices must be integers, not 'str'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nb\OlivOS-Win-0.11.9\./plugin/tmp\OlivOSOnebotV11\eventRouter.py", line 279, in doRouter
  File "C:\Users\Administrator\Desktop\nb\OlivOS-Win-0.11.9\./plugin/tmp\OlivOSOnebotV11\eventRouter.py", line 499, in send_group_msg
  File "C:\Users\Administrator\Desktop\nb\OlivOS-Win-0.11.9\./plugin/tmp\OlivOSOnebotV11\eventRouter.py", line 149, in paraRvMapper
TypeError: string indices must be integers, not 'str'
发送测试字符串的包内为
{
	"action":"send_group_msg",
	"params": {
		"group_id":920220179,
		"message":"你好，世界"
	}
}
使用miraiCQ连接onebotv11，进行发送群聊（其实是频道）消息时出现的错误。（读取消息看似没问题，事实上会显示机器人QQ是-1，这大概与酷Q最高上限是19位QQ有关），然后插件获取频道管理员貌似也有点奇怪的问题，总之没成功，可能是因为权限组不一样（？）。

**Comment by HSTKChiyuki** [comment]
对了，我还发现一件事，如果json请求内没有发送echo这个项的话，这条请求是会被忽略的

**Comment by lunzhiPenxil** [comment]
该问题已在近期版本中解决
[0.9.4，解决对于频道的兼容性问题](https://github.com/lunzhiPenxil/OlivOSOnebotV11/commit/201b1f1b058a0dcc10e4ee38b6daffb40580a863)
